docker:
     permissions:      #added
      packages: write  #added
     runs-on: ubuntu-latest
     needs:
     - code-coverage
     - unit-testing
     steps:
     - uses: actions/checkout@v4
     - uses: docker/login-action@v3
       with:
        registry: ghcr.io
        username: '${{ github.repository_owner }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
     - uses: docker/build-push-action@v6
       with:
        context: .
        push: true
        tags: 'ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}'
